package co.kr.leehana.handler;

import lombok.Getter;
import lombok.Setter;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * @author Hana Lee
 * @since 2015-10-28 22-43
 */
@ManagedBean(name = "radioEx")
@RequestScoped
public class RadioExBean implements Serializable {

	private static final long serialVersionUID = -1956706051080415565L;

	@Setter
	@Getter
	private String favColor1;

	@Setter
	@Getter
	private String favColor2;

	@Setter
	@Getter
	private String favColor3;

	private static Map<String, Object> favColor2Value;
	static {
		favColor2Value = new LinkedHashMap<>();
		favColor2Value.put("Color2 - Red", "Red"); // label, value
		favColor2Value.put("Color2 - Green", "Green");
		favColor2Value.put("Color2 - Blue", "Blue");
	}

	public Map<String, Object> getFavColor2Value() {
		return favColor2Value;
	}

	// Generated by Object array
	public static class Color {
		private String colorLabel;
		private String colorValue;

		public Color(String colorLabel, String colorValue) {
			this.colorLabel = colorLabel;
			this.colorValue = colorValue;
		}

		public String getColorLabel() {
			return colorLabel;
		}

		public String getColorValue() {
			return colorValue;
		}
	}

	private Color[] color3List;

	public Color[] getFavColor3Value() {
		color3List = new Color[3];
		color3List[0] = new Color("Color3 - Red", "Red");
		color3List[1] = new Color("Color3 - Green", "Green");
		color3List[2] = new Color("Color3 - Blue", "Blue");

		return color3List;
	}
}
